version: 'latest'
services:
  api: 
    build:
      context: .
      dockerfile: dockerfile
    command: uvicorn src.run:api --reload --host 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - .:/workspace:rw